# Generated by Django 5.2.3 on 2025-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_agendamento",
                    models.DateTimeField(verbose_name="Data do Agendamento"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observacoes"),
                ),
                (
                    "realizado",
                    models.BooleanField(default=False, verbose_name="Realizado"),
                ),
                (
                    "data_realizacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Realização"
                    ),
                ),
            ],
        ),
    ]
