# Generated by Django 5.2.3 on 2025-06-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("obra", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="entregador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="obra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="obra.obra"
            ),
        ),
    ]
