# Generated by Django 5.0.14 on 2025-06-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('obra', '0004_obra_numero_alter_obra_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('montador', models.CharField(max_length=100)),
                ('data_agendamento', models.DateField()),
                ('realizado', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='obra.obra')),
            ],
        ),
    ]
