# Generated by Django 5.0.14 on 2025-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agendamento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
