# Generated by Django 5.0.14 on 2025-07-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendamento_montador'),
        ('obra', '0004_obra_numero_alter_obra_data_criacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_agendamento'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(verbose_name='Data de Agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='montador',
            field=models.ForeignKey(limit_choices_to={'ativo': True, 'cargo__nome': 'Montador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Montador Responsável'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='obra.obra', verbose_name='Obra relacionada'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='Agendamento Realizado?'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('montador', 'data_agendamento'), name='unique_montador_agendamento', violation_error_message='Esse montador ja tem um agendamento para esse horario.'),
        ),
    ]
