# Generated by Django 5.0.14 on 2025-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_agendamento_options_remove_agendamento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
