# Generated by Django 5.0.14 on 2025-07-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_agendamento_data_criacao'),
        ('obra', '0007_alter_obra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_secundario', to='obra.Obra'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
