

# Generated by Django X.Y on 2023-06-20 12:00

from django.db import migrations

def atualizar_status(apps, schema_editor):
    Agendamento = apps.get_model('agenda', 'Agendamento')
    
    for agendamento in Agendamento.objects.all():
        if agendamento.cancelado:
            agendamento.status = 'cancelada'
        elif agendamento.concluido:
            agendamento.status = 'concluido'
        elif agendamento.data_agendamento:
            agendamento.status = 'em_andamento'
        else:
            agendamento.status = 'pendente'
        agendamento.save()

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '000x_previous_migration'),
    ]

    operations = [
        migrations.RunPython(atualizar_status),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_remove_agenda_entregador_remove_agenda_obra_and_more'),
    ]

    operations = [
    ]
