# Generated by Django 5.0.14 on 2025-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_atualizar_status_existente'),
    ]

    operations = [
    ]
