# Generated by Django 5.2.3 on 2025-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="nome")),
                (
                    "Endereco",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="endereço"
                    ),
                ),
                ("data_criacao", models.DateTimeField(verbose_name="Data de criação")),
                (
                    "cliente",
                    models.CharField(max_length=50, verbose_name="nome cliente"),
                ),
                (
                    "previsao_entrega",
                    models.DateTimeField(verbose_name="Data prevista para entrega"),
                ),
            ],
        ),
    ]
