# Generated by Django 5.0.14 on 2025-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
    ]
