# Generated by Django 5.0.14 on 2025-06-24 14:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_add_numero_controle_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='Endereco',
        ),
        migrations.AlterField(
            model_name='obra',
            name='previsao_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data prevista para entrega'),
        ),
        migrations.AddField(
            model_name='obra',
            name='endereco',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='endereço'),
        ),
    ]
