# Generated by Django 5.0.14 on 2025-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0003_remove_obra_endereco_obra_numero_controle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='numero controle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
