# Generated by Django 5.0.14 on 2025-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0004_obra_numero_alter_obra_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
