# Generated by Django 5.0.14 on 2025-07-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0006_obra_data_alteracao_obra_data_exclusao_obra_excluido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
    ]
