# Generated by Django 5.0.14 on 2025-07-22 09:35

from django.db import migrations, models

def sincronizar_status(apps, schema_editor):
    Obra = apps.get_model('obras', 'Obra')
    for obra in Obra.objects.all():
        obra.agendamentos.update(status=obra.status)

class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0008_alter_obra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('Realizado', 'Realizado'), ('cancelada', 'Cancelada'), ('excluida', 'Excluída')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
